// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWykwtztqfUsx9iDWZzv6zS_VRrFVtgI',
    appId: '1:186333214756:web:8dea72d1d6da34a3f9c0b1',
    messagingSenderId: '186333214756',
    projectId: 'zendiet-e2110',
    authDomain: 'zendiet-e2110.firebaseapp.com',
    storageBucket: 'zendiet-e2110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvpmnv-H46TL8xvTOT5UNEQyr0qjZRbb8',
    appId: '1:186333214756:android:def5ebaca7c63830f9c0b1',
    messagingSenderId: '186333214756',
    projectId: 'zendiet-e2110',
    storageBucket: 'zendiet-e2110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfKOzjD6nihbToVKNoJT9NjLpvjyPFoE',
    appId: '1:186333214756:ios:8e0efec7afae855af9c0b1',
    messagingSenderId: '186333214756',
    projectId: 'zendiet-e2110',
    storageBucket: 'zendiet-e2110.appspot.com',
    iosBundleId: 'com.example.zendiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhfKOzjD6nihbToVKNoJT9NjLpvjyPFoE',
    appId: '1:186333214756:ios:8e0efec7afae855af9c0b1',
    messagingSenderId: '186333214756',
    projectId: 'zendiet-e2110',
    storageBucket: 'zendiet-e2110.appspot.com',
    iosBundleId: 'com.example.zendiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWykwtztqfUsx9iDWZzv6zS_VRrFVtgI',
    appId: '1:186333214756:web:5267fc30a276a0c7f9c0b1',
    messagingSenderId: '186333214756',
    projectId: 'zendiet-e2110',
    authDomain: 'zendiet-e2110.firebaseapp.com',
    storageBucket: 'zendiet-e2110.appspot.com',
  );
}
